require('dotenv').config();
const mongoose = require('mongoose');
const crypto = require('crypto');
const nodemailer = require('nodemailer');
const User = require('./schemas/users');
const Role = require('./schemas/roles');

// --- CẤU HÌNH MAILTRAP ---
const transporter = nodemailer.createTransport({
    host: "sandbox.smtp.mailtrap.io",
    port: 2525,
    auth: {
        user: process.env.MAILTRAP_USER,
        pass: process.env.MAILTRAP_PASS
    }
});

// Hàm tạo ngẫu nhiên chuỗi 16 kí tự
function generateRandomPassword() {
    return crypto.randomBytes(8).toString('hex'); // => 16 characters
}

// Hàm gửi email
async function sendPasswordEmail(email, username, password) {
    try {
        await transporter.sendMail({
            from: '"Admin App" <admin@haha.com>',
            to: email,
            subject: "Thông tin tài khoản đăng nhập của bạn",
            text: `Chào ${username},\n\nTài khoản của bạn đã được tạo thành công.\nUsername: ${username}\nPassword: ${password}\n\nVui lòng bảo mật thông tin này.`,
            html: `<p>Chào <b>${username}</b>,</p>
                   <p>Tài khoản của bạn đã được tạo thành công.</p>
                   <ul>
                     <li><b>Username:</b> ${username}</li>
                     <li><b>Password:</b> ${password}</li>
                   </ul>
                   <p>Vui lòng bảo mật thông tin này.</p>`,
        });
        console.log(`[Email] Đã gửi thông tin đăng nhập thành công cho ${email}`);
    } catch (error) {
        console.error(`[Email Lỗi] Không thể gửi mail cho ${email}:`, error);
    }
}

// Hàm delay để tránh bị chặn IP / rate limit trên Mailtrap Sandbox
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function importUsers() {
    try {
        // Kết nối MongoDB
        console.log("Đang kết nối tới cơ sở dữ liệu MongoDB...");
        await mongoose.connect('mongodb://localhost:27017/NNPTUD-C6');
        console.log("✅ Đã kết nối MongoDB");

        // Tìm role của user trong DB
        // Tên role thường là "USER", "user", "ROLE_USER" tuỳ vào dữ liệu hiện tại
        // Sẽ thử tìm các tên thông dụng
        let role = await Role.findOne({ name: { $in: ["USER", "user", "ROLE_USER"] } });
        if (!role) {
            console.log("⚠️ Không tìm thấy Role User có sẵn (USER/user/ROLE_USER). Đang tạo Role mới...");
            role = await Role.create({ name: 'USER', description: 'User role generated by script' });
        }
        console.log(`✅ Sử dụng Role ID: ${role._id} (${role.name})`);

        console.log("Bắt đầu đọc dữ liệu từ file user.xlsx...");
        const xlsx = require('xlsx');
        const workbook = xlsx.readFile('user.xlsx');
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        let usersData = xlsx.utils.sheet_to_json(worksheet);

        console.log(`Tìm thấy ${usersData.length} users trong file Excel. Bắt đầu Import...`);

        for (let row of usersData) {
            const username = row.username;
            const email = row.email;

            if (!username || !email) {
                console.log(`[Bỏ qua] Dòng thiếu dữ liệu username hoặc email.`);
                continue;
            }

            const rawPassword = generateRandomPassword();

            // Kiểm tra xem user này đã tồn tại chưa để tránh lỗi MongoDB unique index
            let existingUser = await User.findOne({ 
                $or: [{ username: username }, { email: email }]
            });

            if (existingUser) {
                console.log(`[Bỏ qua] User '${username}' hoặc email '${email}' đã tồn tại trong database.`);
                continue;
            }

            // Tạo người dùng dưới database
            const newUser = new User({
                username: username,
                email: email,
                password: rawPassword, // Password sẽ tự động được mã hoá theo hook pre('save') trong schemas/users.js
                role: role._id
            });

            await newUser.save();
            console.log(`[Thêm mới] Tạo thành công user: ${username} | Pass ban đầu: ${rawPassword}`);
            
            // Chạy gửi mail
            await sendPasswordEmail(email, username, rawPassword);

            // Delay khoảng 2 giây để không bị khóa (Rate Limit) ở Mailtrap miễn phí (chỉ cho phép tối đa 2 email / giây)
            await delay(2000); 
        }

        console.log("🎉 XONG! Quá trình import hoàn thành.");

    } catch (error) {
        console.error("❌ Xảy ra lỗi trong quá trình import:", error);
    } finally {
        await mongoose.disconnect();
        console.log("Đã ngắt kết nối database.");
    }
}

importUsers();
